WITH DELAY_BASED_ON_WEEKDAY(
    SELECT
        AVG(ARR_DELAY) AS AVERAGE_DELAY,
        CASE
            WHEN DAYOFWEEK(FL_DATE) IN (6,7)
                THEN 'WEEKEND'
            ELSE 'WEEK'
        END AS WEEK_DAY,
        ORIGIN,
        DEST,
        OP_UNIQUE_CARRIER
    FROM ffx
    WHERE ORIGIN = 'SFO'
        AND DEST_CITY_NAME = 'New York, NY'
    GROUP BY 2,3,4,5
    ORDER BY 1 ASC
)

SELECT
    MIN(AVERAGE_DELAY),
    WEEK_DAY,
    OP_UNIQUE_CARRIER
FROM DELAY_BASED_ON_WEEKDAY
GROUP BY 2,3
ORDER BY 1 ASC